---
# tasks file for debops.telegraf

- name: Enable telegraf service
  service:
    name: telegraf
    enabled: yes
    state: started

- name: Configure Telegraf
  template:
    src: 'etc/telegraf/telegraf.conf.j2'
    dest: '/etc/telegraf/telegraf.conf'
  notify:
    - 'Restart telegraf'
